### ISSUE TITLE
Crash with aiohttp 3.1.x related to use of StreamReader

### ISSUE THREAD

**Issue by adamrothman** [aio-libs/aiobotocore#551]
I'm getting a crash using aiobotocore 0.6.0 with aiohttp 3.1.0 (released yesterday 2018-03-21). It appears to be related to botocore's response checking:

```
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    loop.run_until_complete(main())
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "test.py", line 12, in main
    response = await client.describe_table(TableName='orbit-prod-identities')
  File "/Users/adam/Desktop/aiobotocore-test/venv/lib/python3.6/site-packages/aiobotocore/client.py", line 94, in _make_api_call
    operation_model, request_dict)
  File "/Users/adam/Desktop/aiobotocore-test/venv/lib/python3.6/site-packages/aiobotocore/endpoint.py", line 290, in _send_request
    exception)):
  File "/Users/adam/Desktop/aiobotocore-test/venv/lib/python3.6/site-packages/aiobotocore/endpoint.py", line 322, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/Users/adam/Desktop/aiobotocore-test/venv/lib/python3.6/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Users/adam/Desktop/aiobotocore-test/venv/lib/python3.6/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Users/adam/Desktop/aiobotocore-test/venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Users/adam/Desktop/aiobotocore-test/venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/Users/adam/Desktop/aiobotocore-test/venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/adam/Desktop/aiobotocore-test/venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/Users/adam/Desktop/aiobotocore-test/venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 220, in __call__
    return self._check_response(attempt_number, response)
  File "/Users/adam/Desktop/aiobotocore-test/venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 335, in _check_response
    actual_crc32 = crc32(response[0].content) & 0xffffffff
TypeError: a bytes-like object is required, not 'StreamReader'
```

Here's a minimal reproducer:

```python
# -*- coding: utf-8 -*-
import asyncio
from pprint import pprint

import aiobotocore


async def main():
    session = aiobotocore.get_session()
    client = session.create_client('dynamodb')

    response = await client.list_tables()
    pprint(response)

    await client.close()


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```

I've also tried `client.describe_table`, which results in the same error. It seems like the semantics for `StreamReader` have changed such that it can no longer be treated like data.

The crash does not occur with aiohttp 3.0.9.

Environment:
* Python 3.6.4
* aiobotocore 0.6.0
* aiohttp 3.1.0
* botocore 1.8.21

**Comment by thehesiod** [comment]
ya, we should have caught in https://github.com/aio-libs/aiobotocore/pull/536 that aiohttp needs to be upper-bound version locked.

**Comment by asvetlov** [comment]
Sorry, guys. My personal fault.
Support for sending `StreamReader` was dropped. I wanted to replace it with support for *any* async iterator by aio-libs/aiohttp/issues/2802

But I did run too fast.
Now I think the lost functionality is a critical bug, it will be fixed by pushing *async iterator* feature into next 3.1 bugfix release (coming soon).

Sorry again.
@thehesiod could you postpone the locking aiohttp upper version?

As alternative I see the commitment on publishing a new aiobotocore version with the lock raised up to the latest aiohttp after every aiohttp release if tests are passed. It looks too complex burden.

On my side I wish to use the latest aiobotocore with the latest aiohttp (my company uses both libraries).
I know about aiobotocore pain related to timeouts but I see a big progress on aio-libs/aiohttp/issues/2768
The first PR aio-libs/aiohttp/pull/2842 is not perfect from my perspective but personally I've got a vision how user interface would look like.
I'm expecting to land new timeouts on aiohttp 3.2 1-2 months from now.

**Comment by thehesiod** [comment]
@asvetlov no worries!  will do

**Comment by adamrothman** [comment]
Thanks guys, libraries these and maintainers like you are why I love Python. 🤗

**Comment by asvetlov** [comment]
Fixed by aiohttp 3.1.1 release

**Comment by adamrothman** [comment]
@asvetlov I'm still getting the same crash after updating to aiohttp 3.1.1:

```
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    loop.run_until_complete(main())
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "test.py", line 13, in main
    response = await client.list_tables()
  File "/Users/adam/Desktop/aiobotocore-test/venv/lib/python3.6/site-packages/aiobotocore/client.py", line 94, in _make_api_call
    operation_model, request_dict)
  File "/Users/adam/Desktop/aiobotocore-test/venv/lib/python3.6/site-packages/aiobotocore/endpoint.py", line 290, in _send_request
    exception)):
  File "/Users/adam/Desktop/aiobotocore-test/venv/lib/python3.6/site-packages/aiobotocore/endpoint.py", line 322, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/Users/adam/Desktop/aiobotocore-test/venv/lib/python3.6/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Users/adam/Desktop/aiobotocore-test/venv/lib/python3.6/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Users/adam/Desktop/aiobotocore-test/venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Users/adam/Desktop/aiobotocore-test/venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/Users/adam/Desktop/aiobotocore-test/venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/adam/Desktop/aiobotocore-test/venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/Users/adam/Desktop/aiobotocore-test/venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 220, in __call__
    return self._check_response(attempt_number, response)
  File "/Users/adam/Desktop/aiobotocore-test/venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 335, in _check_response
    actual_crc32 = crc32(response[0].content) & 0xffffffff
TypeError: a bytes-like object is required, not 'StreamReader'
```

**Comment by thehesiod** [comment]
ya, seems like `ClientResponse.content` is `StreamReader` and not string/bytes anymore

**Comment by asvetlov** [comment]
But `ClientResponse.content` was a `StreamReader` from time of birth.
3.3.1 restored a broken/removed functionality for passing a content as a body: `await client.post(url, data=resp.content)`, nothing more.

**Comment by thehesiod** [comment]
@asvetlov @adamrothman figured it out, looks like `ClientResponse._content` was renamed to `ClientResponse._body`.  Fix will be in: https://github.com/aio-libs/aiobotocore/pull/564

**Comment by thehesiod** [comment]
fixed with https://github.com/aio-libs/aiobotocore/pull/569

**Comment by nitrocode** [comment]
Thank you for fixing this issue. I just tripped over it on the `0.6.0` version. I tried upgrading and it looks like [`0.6.1` has not been published to pypi](https://pypi.org/project/aiobotocore/). Do you mind publishing it @thehesiod ?

**Comment by jettify** [comment]
Probably due to typo `0.6.1a0` was published https://pypi.org/project/aiobotocore/0.6.1a0/

**Comment by thehesiod** [comment]
very weird, I don't remember putting a0

**Comment by jettify** [comment]
https://pypi.org/project/aiobotocore/0.7.0/ released new version

**Comment by jettify** [comment]
sigh, this time RST formatting is broken on PyPI

**Comment by thehesiod** [comment]
weird, how did that happen?

**Comment by jettify** [comment]
I edited changes.rst and broke formatting  https://github.com/aio-libs/aiobotocore/pull/571 , anyway added command to test RST correctness.

**Comment by French-Noodles** [comment]
So is there any fix for this now? im kinda confused on how to do it

```
async def requestingresponse():
  async with aiohttp.ClientSession() as cs:
    async with cs.get(url) as res:
      response = res
      bytes = BytesIO(response._body)
      img = Image.open(bytes)
      img.show()  

asyncio.run(requestingresponse())
```

this is my code but now im getting this error after i changed .content to ._body 
```
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x00000272F288E6D0>
```

**Comment by thehesiod** [comment]
you can't directly pass response['Body'] to BytesIO as it's an async stream

**Comment by HarryLinux** [comment]
How can the `StreamReader` be written to a file as bytes?
